var posts = [{ title: "How Crocodiles Cross Oceans", article: "How did the world's largest living reptile, the saltwater crocodile, reach so many South Pacific islands separated by huge stretches of water despite being a poor swimmer? Apparently, like a surfer catching a wave, these goliaths can ride currents on the ocean surface to cross large areas of open sea, researchers now reveal. The saltwater or estuarine crocodile (Crocodylus porosus) is a ferocious giant that can grow at least 23 feet long (7 meters) and weigh more than 2,200 pounds (1000 kilograms). These scaly monsters have been known to devour sharks, and even attack things they can't eat, often assaulting boats in the mistaken belief they are rivals or prey, biting down with nearly 2 tons of pressure — powerful enough to crush bone or punch through aluminum hulls..." }, { title: "Lemur Species", article: "Exact classification of some types of lemurs is a subject of debate, but it's generally accepted that there are five families of lemurs with about a dozen genera and just over 30 living species. Some species of lemurs are now extinct, including one ancient lemur said to be as large as a gorilla — over 400 pounds. Some prosimian species contain a number of subspecies, all with distinct characteristics, which brings the total types of living lemurs to around 50. Today's lemur species range in size from the tiny pygmy mouse lemur, weighing in at about an ounce, to the 15-pound indri lemur and the sifaka, which are both about the size of a standard house cat..." }, { title: "Aldabra Tortoise", article: "The Aldabra tortoise is becoming more commonly available in the pet trade the world over, but it is still considered one of the more specialized tortoises. The Aldabra tortoise, because of its potential large size, requires a good deal of space and special consideration. Moving a tortoise that is more than 200 lbs is bad enough, but moving one that is more than 400 lbs can be problematic especially if the animal does not want to move or cannot. The Aldabra tortoise is only protected as far as trade so no special permits are required to keep and maintain these in captivity...." }];

riot.route.start(true);

riot.route('/post/*', function (id) {
  riot.mount('main', 'post', posts[id]);
});

riot.mount('navigation');
